package photograd.kz.photograd.models.enums


enum class ErrorCodeTypeDescription(val value: String)
{
    user_not_exist ( "Данного пользователя не существует."),
    incorrect_password_or_email ( "Неверный логин или пароль."),
    session_not_exist ( "Данной сессии не существует."),
    active_mission_exists ( "У пользователя уже имеется активная миссия."),
    mission_not_exist ( "Данной миссии не существует."),
    no_active_mission ( "У пользователя нет активной миссии."),
    game_not_exist ( "Данной игры не существует."),
    user_not_challenged ( "Пользователь, которому брошен вызов, не является игроком."),
    not_challenging_game ( "Игра не находится в состоянии вызова."),
    gameround_not_exist ( "Данного игрового раунда не существует."),
    category_not_exist ( "Данной категории не существует."),
    user_not_starting_round ( "Пользователь не является игроком, начинающим раунд."),
    gameround_already_finished ( "Раунд уже завершен."),
    question_instance_not_exist ( "Данного экземпляра вопроса не существует."),
    answer_option_not_exist ( "Данного варианта ответа не существует."),
    category_already_selected ( "Категория раунда уже выбрана."),
    offer_not_exist ( "Данного предложения не существует."),
    not_enough_apples ( "У Вас недостаточно яблок для покупки."),
    not_enough_apples_message ( "Накопите достаточное количество яблок."),
    user_not_playing_game ( "Пользователь не играет в данную игру."),
    game_already_finished ( "Данная игра уже завершена."),
    user_already_exists ( "Пользователь уже существует."),
    user_already_in_friendlist ( "Пользователь уже добавлен в список друзей."),
    image_file_error ( "Изображение не существует или его невозможно открыть."),
    friendship_request_already_sent ( "Запрос на добавление в друзья уже отправлен."),
    no_such_friendship_request ( "Такого запроса на добавление в друзья не существует."),
    accepting_not_friendship_request ( "Запрос на добавление в друзья уже обработан."),
    declining_not_friendship_request ( "Запрос на отклонение от добавления в друзья уже обработан."),
    partner_mission_not_exist ( "Такой партнерской миссии не существует."),
    partner_mission_is_not_active ( "Данная миссия уже неактивна."),
    already_playing_partner_mission ( "Уже есть активная игра в этой миссии."),
    purchase_not_exist ( "Данной покупки не существует."),
    not_user_purchase ( "Данная покупка принадлежит другому пользователю."),
    no_active_mission_attempt ( "У пользователя нет активной попытки прохождения миссии."),
    user_not_logged_in ( "Пользователь не вошел в систему."),
    empty_username ( "Заполните имя пользователя."),
    empty_email  ( "Пустой email."),
    invalid_email  ( "Некорректный email."),
    incorrect_social_network ( "Неправильно задана социальная сеть."),
    no_offers_left ( "Предложения закончились."),
    should_be_another_user ( "Должен быть другой пользователь."),
    not_valid_game_type ( "Несуществующий тип игры."),
    mission_attempt_not_active ( "Попытка пройти миссию неактивна."),
    mission_attempt_games_amount_exceeded ( "Превышено максимальное количество попыток миссии - 5."),
    mission_attempt_games_amount_exceeded_message ( "Пожалуйста, завершите текущие игры миссии."),
    no_email_in_profile  ( "В Вашем профиле не задан email."),
    username_max_length_exceeded  ( "Превышена допустимая длина имени пользователя."),
    mission_reward_expired  ( "Срок годности награды истек."),
    mission_reward_already_activated  ( "Награда уже активирована."),
    mission_reward_not_exist  ( "Награды уже не существует."),
    mission_reward_already_confirmed  ( "Награда уже подтверждена."),
    purchase_expired  ( "Срок годности покупки истек."),
    purchase_already_activated  ( "Покупка уже активирована."),
    user_not_confirmed  ( "Необходимо подтвердить электронную почту."),
    opponent_not_enough_apples  ( "У оппонента недостаточно яблок."),
    not_user_reward  ( "Награда не принадлежит пользователю."),
    incompatible_api_version  ( "Устаревшая версия."),
    incompatible_api_version_message  ( "Пожалуйста, обновите приложение."),
    birthday_not_set ( "Не задан день рождения"),
    gender_not_set ( "Не задан пол"),
    invalid_gender ( "Некорректный пол"),
    wrong_date_format ( "Неверный формат даты"),
    question_text_too_short	 ( "Слишком короткий текст вопроса"),
    opponent_can_not_play ( "Соперник не может играть в дуэли"),
    need_to_play_mission ( "Пройдите 1 миссию"),
    email_already_registered ( "Данный email уже зарегистрирован"),
    user_is_blocked ( "Аккаунт пользователя заблокирован"),
    personal_info_not_set ( "Не заданы пользовательские данные"),
    offer_user_purchases_out_of_limit	( "Превышено ограничение на общее количество покупок"),
    offer_user_purchases_out_of_period_limit	 ( "Превышено временное ограничение на покупку"),
}