package photograd.kz.photograd.models

/**
 * Created by wokrey@gmail.com on 7/4/19.
 * It's not wokrey, if the code smells bad. Somebody set me up.
 */
object ApiMethods {

    const val SOCIAL_AUTH = "social_user_login"
    const val GET_OFFER_INFO = "get_offer_info"
    const val REGISTRATION = "registration"
    const val RESET_PASSWORD = "reset_password"
    const val USER_LOGIN = "user_login"
    const val USER_AUTH = "user_auth"
    const val GET_CURRENT_GAMES = "get_current_games"
    const val GET_MISSIONS_DATA = "get_missions_data"
    const val GET_MISSIONS = "get_missions"
    const val GET_FRIENDS = "get_friends"
    const val GET_DATA = "get_data"
    const val GET_USER_STATISTICS = "get_user_statistics"
    const val GET_TOP_RATING = "get_top_rating"
    const val GET_FRIENDS_RATING = "get_friends_rating"
    const val GET_OFFERS = "get_offers2"
    const val GET_OFFER_CATEGORIES = "get_offer_categories"
    const val GET_GAME = "get_game"
    const val GET_CATEGORIES = "get_categories_for_selection"
    const val SELECT_CATEGORY = "select_category"
    const val SUBMIT_ANSWERS = "submit_answers"
    const val CHALLENGE_RANDOM_USER = "challenge_random_user"
    const val GET_PARTNER_MISSION_RATING = "get_partner_mission_rating"
    const val PLAY_PARTNER_MISSION = "play_partner_mission"
    const val PLAY_MISSION = "play_mission"
    const val GIVE_UP_MISSION = "give_up_mission"
    const val FIND_PLAYERS = "find_players"
    const val FRIENDSHIP_REQUEST = "friendship_request"
    const val DECLINE_FRIENDSHIP = "decline_friendship"
    const val ACCEPT_GAME = "accept_game"
    const val DECLINE_GAME = "decline_game"
    const val GIVE_UP_GAME = "give_up_game"
    const val CHALLENGE_USER = "challenge_user"
    const val CONFIRM_NOTIFICATIONS = "confirm_notifications"
    const val SOCIAL_USER_LOGIN = "social_user_login"
    const val UPLOAD_IMAGE = "upload_image"
    const val GET_USER = "get_user"
    const val GET_PURCHASES = "get_purchases"
    const val PURCHASE_OFFER = "purchase_offer"
    const val ACTIVATE_PURCHASE = "activate_purchase"
    const val ACTIVATE_REWARD = "activate_reward"
    const val USER_LOGOUT = "user_logout"
    const val RESEND_CONFIRMATION_EMAIL = "resend_confirmation_email"
    const val CREATE_QUESTION = "create_question"
    const val UPDATE_PROFILE = "update_profile"
}